pipeline {
    agent none

    stages {
        stage('build') {
            when {
                changeset "**/vote/**"
            }

            agent {
                docker {
                    image 'eeganlf/voteapp-python:v0.1.0'
                }
            }

            steps {
                echo 'Compiling vote app...'
                dir('vote') {
                    sh 'mvn compile'
                }
            }
        }
        
        stage('test') {
            when {
                changeset "**/vote/**"
            }

            agent {
                docker {
                    image 'eeganlf/voteapp-python:v0.1.0'
                }
            }

            steps {
                echo 'Running Unit Tests on vote app...'
                dir('vote') {
                    sh 'mvn clean test'
                }
            }
        }
        
        stage('docker-package') {
            agent any
            
            when {
                branch 'master'
                changeset "**/vote/**"
            }

            steps {
                echo 'Packaging vote app with docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/','dockerlogin') {
                        def voteImage = docker.build("sixfold0981/vote:v${env.BUILD_ID}", "./vote")
                        voteImage.push()
                        voteImage.push("latest")
                    }
                }
            }
        }
    }
    
    post {
        always {
            echo 'Building multibranch pipeline for vote is completed...'
        }
    }
}
